<?php

/**
 * @file
 * Contains exide_hello_world2.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function exide_hello_world2_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the exide_hello_world2 module.
    case 'help.page.exide_hello_world2':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Hello World2 module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function exide_hello_world2_theme() {
  return [
    'exide_hello_world2' => [
      'render element' => 'children',
    ],
  ];
}
